exports.STATUS_UNAVAILABLE = 'UNAVAILABLE';
exports.STATUS_AVAILABLE = 'AVAILABLE';
exports.STATUS_HOLDING = 'HOLDING';

exports.STATUS_CONFIRM = 'SUCCESSFUL';
exports.STATUS_FAIL = 'FAIL';
exports.STATUS_PENDING = 'PENDING';

exports.STATUS_ROLL_ADMIN = 'ADMIN';
exports.STATUS_ROLL_USER = 'USER';
exports.STATUS_ROLL_GUEST = 'GUEST';
exports.APARTMENT01 = 'THE MONT TOWER';
